version: '2'

services:
  books-app:
    image: 'books:latest'
    container_name: books-app
    depends_on:
      books-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://books-db:5432/books-db
      - SPRING_DATASOURCE_USERNAME=books-db-user
      - SPRING_DATASOURCE_PASSWORD=books-db-password
    ports:
      - 8082:8080
  books-db:
    image: 'postgres:16-alpine'
    container_name: books-db
    environment:
      - POSTGRES_DB=books-db
      - POSTGRES_USER=books-db-user
      - POSTGRES_PASSWORD=books-db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d books-db -U books-db-user"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5434:5432
