version: '2'

services:
  books-app:
    image: 'books:latest'
    container_name: books-app
    depends_on:
      books-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://books-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    ports:
      - 8082:8080
  books-db:
    image: 'postgres:16-alpine'
    container_name: books-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U compose-postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
