version: '2'

services:
  books-app:
    image: 'books:latest'
    container_name: books-app
    depends_on:
      - books-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://books-db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
    ports:
      - 8082:8080
  books-db:
    image: 'postgres:16'
    container_name: books-db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
