CREATE SEQUENCE book_seq
START WITH 1
INCREMENT BY 50;

CREATE TABLE book (
  id BIGINT NOT NULL,
  author VARCHAR(255),
  title VARCHAR(255)
);

ALTER TABLE book
ADD CONSTRAINT pk_book_id PRIMARY KEY(id);
